
################################################################
# This is a generated script based on design: cips
#
# Though there are limitations about the generated script,
# the main purpose of this utility is to make learning
# IP Integrator Tcl commands easier.
################################################################

namespace eval _tcl {
proc get_script_folder {} {
   set script_path [file normalize [info script]]
   set script_folder [file dirname $script_path]
   return $script_folder
}
}
variable script_folder
set script_folder [_tcl::get_script_folder]

################################################################
# Check if script is running in correct Vivado version.
################################################################
set scripts_vivado_version 2024.2
set current_vivado_version [version -short]

if { [string first $scripts_vivado_version $current_vivado_version] == -1 } {
   puts ""
   if { [string compare $scripts_vivado_version $current_vivado_version] > 0 } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2042 -severity "ERROR" " This script was generated using Vivado <$scripts_vivado_version> and is being run in <$current_vivado_version> of Vivado. Sourcing the script failed since it was created with a future version of Vivado."}

   } else {
     catch {common::send_gid_msg -ssname BD::TCL -id 2041 -severity "ERROR" "This script was generated using Vivado <$scripts_vivado_version> and is being run in <$current_vivado_version> of Vivado. Please run the script in Vivado <$scripts_vivado_version> then open the design in Vivado <$current_vivado_version>. Upgrade the design by running \"Tools => Report => Report IP Status...\", then run write_bd_tcl to create an updated script."}

   }

   return 1
}

################################################################
# START
################################################################

# To test this script, run the following commands from Vivado Tcl console:
# source cips_script.tcl

# If there is no project opened, this script will create a
# project, but make sure you do not have an existing project
# <./myproj/project_1.xpr> in the current working folder.

set list_projs [get_projects -quiet]
if { $list_projs eq "" } {
   create_project project_1 myproj -part xcvp1902-vsva6865-2MP-e-S
}


# CHANGE DESIGN NAME HERE
variable design_name
set design_name cips

# If you do not already have an existing IP Integrator design open,
# you can create a design using the following command:
#    create_bd_design $design_name

# Creating design if needed
set errMsg ""
set nRet 0

set cur_design [current_bd_design -quiet]
set list_cells [get_bd_cells -quiet]

if { ${design_name} eq "" } {
   # USE CASES:
   #    1) Design_name not set

   set errMsg "Please set the variable <design_name> to a non-empty value."
   set nRet 1

} elseif { ${cur_design} ne "" && ${list_cells} eq "" } {
   # USE CASES:
   #    2): Current design opened AND is empty AND names same.
   #    3): Current design opened AND is empty AND names diff; design_name NOT in project.
   #    4): Current design opened AND is empty AND names diff; design_name exists in project.

   if { $cur_design ne $design_name } {
      common::send_gid_msg -ssname BD::TCL -id 2001 -severity "INFO" "Changing value of <design_name> from <$design_name> to <$cur_design> since current design is empty."
      set design_name [get_property NAME $cur_design]
   }
   common::send_gid_msg -ssname BD::TCL -id 2002 -severity "INFO" "Constructing design in IPI design <$cur_design>..."

} elseif { ${cur_design} ne "" && $list_cells ne "" && $cur_design eq $design_name } {
   # USE CASES:
   #    5) Current design opened AND has components AND same names.

   set errMsg "Design <$design_name> already exists in your project, please set the variable <design_name> to another value."
   set nRet 1
} elseif { [get_files -quiet ${design_name}.bd] ne "" } {
   # USE CASES: 
   #    6) Current opened design, has components, but diff names, design_name exists in project.
   #    7) No opened design, design_name exists in project.

   set errMsg "Design <$design_name> already exists in your project, please set the variable <design_name> to another value."
   set nRet 2

} else {
   # USE CASES:
   #    8) No opened design, design_name not in project.
   #    9) Current opened design, has components, but diff names, design_name not in project.

   common::send_gid_msg -ssname BD::TCL -id 2003 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

   create_bd_design $design_name

   common::send_gid_msg -ssname BD::TCL -id 2004 -severity "INFO" "Making design <$design_name> as current_bd_design."
   current_bd_design $design_name

}

common::send_gid_msg -ssname BD::TCL -id 2005 -severity "INFO" "Currently the variable <design_name> is equal to \"$design_name\"."

if { $nRet != 0 } {
   catch {common::send_gid_msg -ssname BD::TCL -id 2006 -severity "ERROR" $errMsg}
   return $nRet
}

set bCheckIPsPassed 1
##################################################################
# CHECK IPs
##################################################################
set bCheckIPs 1
if { $bCheckIPs == 1 } {
   set list_check_ips "\ 
xilinx.com:ip:ps_wizard:1.0\
xilinx.com:ip:axi_noc:1.1\
"

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

}

if { $bCheckIPsPassed != 1 } {
  common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
  return 3
}

##################################################################
# DESIGN PROCs
##################################################################



# Procedure to create entire design; Provide argument to make
# procedure reusable. If parentCell is "", will use root.
proc create_root_design { parentCell } {

  variable script_folder
  variable design_name

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set sys_clk0_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 sys_clk0_0 ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {102564000} \
   ] $sys_clk0_0

  set sys_clk1_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 sys_clk1_0 ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {102564000} \
   ] $sys_clk1_0

  set CH0_DDR4_0_0 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 CH0_DDR4_0_0 ]

  set CH0_DDR4_1_0 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 CH0_DDR4_1_0 ]

  set S08_AXI_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S08_AXI_0 ]
  set_property -dict [ list \
   CONFIG.ADDR_WIDTH {64} \
   CONFIG.ARUSER_WIDTH {0} \
   CONFIG.AWUSER_WIDTH {0} \
   CONFIG.BUSER_WIDTH {0} \
   CONFIG.DATA_WIDTH {256} \
   CONFIG.FREQ_HZ {5000000} \
   CONFIG.HAS_BRESP {1} \
   CONFIG.HAS_BURST {1} \
   CONFIG.HAS_CACHE {1} \
   CONFIG.HAS_LOCK {1} \
   CONFIG.HAS_PROT {1} \
   CONFIG.HAS_QOS {1} \
   CONFIG.HAS_REGION {0} \
   CONFIG.HAS_RRESP {1} \
   CONFIG.HAS_WSTRB {1} \
   CONFIG.ID_WIDTH {0} \
   CONFIG.MAX_BURST_LENGTH {256} \
   CONFIG.NUM_READ_OUTSTANDING {2} \
   CONFIG.NUM_READ_THREADS {1} \
   CONFIG.NUM_WRITE_OUTSTANDING {2} \
   CONFIG.NUM_WRITE_THREADS {1} \
   CONFIG.PROTOCOL {AXI4} \
   CONFIG.READ_WRITE_MODE {READ_WRITE} \
   CONFIG.RUSER_BITS_PER_BYTE {0} \
   CONFIG.RUSER_WIDTH {0} \
   CONFIG.SUPPORTS_NARROW_BURST {0} \
   CONFIG.WUSER_BITS_PER_BYTE {0} \
   CONFIG.WUSER_WIDTH {0} \
   ] $S08_AXI_0


  # Create ports
  set clk_5MHz [ create_bd_port -dir I -type clk -freq_hz 5000000 clk_5MHz ]
  set_property -dict [ list \
   CONFIG.ASSOCIATED_BUSIF {S08_AXI_0} \
 ] $clk_5MHz

  # Create instance: versal_cips_0, and set properties
  set versal_cips_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:ps_wizard:1.0 versal_cips_0 ]
  set_property -dict [list \
    CONFIG.PS_PMC_CONFIG(PMC_SMAP_PERIPHERAL) {PRIMARY_ENABLE 1 IO 16_Bit} \
    CONFIG.PS_PMC_CONFIG(PMC_USE_PMC_AXI_NOC0) {1} \
    CONFIG.PS_PMC_CONFIG(PS_ENET1_MDIO) {ENABLE 1 IO PMC_MIO_50:51 IO_TYPE MIO} \
    CONFIG.PS_PMC_CONFIG(PS_ENET1_PERIPHERAL) {ENABLE 1 IO PMC_MIO_38:49 IO_TYPE MIO} \
    CONFIG.PS_PMC_CONFIG(PS_GEN_IPI0_ENABLE) {1} \
    CONFIG.PS_PMC_CONFIG(PS_GEN_IPI1_ENABLE) {1} \
    CONFIG.PS_PMC_CONFIG(PS_GEN_IPI2_ENABLE) {1} \
    CONFIG.PS_PMC_CONFIG(PS_GEN_IPI3_ENABLE) {1} \
    CONFIG.PS_PMC_CONFIG(PS_GEN_IPI4_ENABLE) {1} \
    CONFIG.PS_PMC_CONFIG(PS_GEN_IPI5_ENABLE) {1} \
    CONFIG.PS_PMC_CONFIG(PS_GEN_IPI6_ENABLE) {1} \
    CONFIG.PS_PMC_CONFIG(PS_I2CSYSMON_PERIPHERAL) {ENABLE 0 IO_TYPE MIO IO PMC_MIO_0:1} \
    CONFIG.PS_PMC_CONFIG(PS_SLR_ID) {0} \
    CONFIG.PS_PMC_CONFIG(PS_UART0_PERIPHERAL) {ENABLE 1 IO PMC_MIO_8:9 IO_TYPE MIO} \
    CONFIG.PS_PMC_CONFIG(PS_UART1_PERIPHERAL) {ENABLE 1 IO PMC_MIO_4:5 IO_TYPE MIO} \
    CONFIG.PS_PMC_CONFIG(PS_USE_FPD_AXI_NOC0) {1} \
    CONFIG.PS_PMC_CONFIG(PS_USE_FPD_AXI_NOC1) {1} \
    CONFIG.PS_PMC_CONFIG(PS_USE_FPD_CCI_NOC) {1} \
    CONFIG.PS_PMC_CONFIG(PS_USE_LPD_AXI_NOC0) {1} \
    CONFIG.PS_PMC_CONFIG(SMON_INTERFACE_TO_USE) {I2C} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS0) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCCAUX_110 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 47} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS1) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCCAUX_111 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 48} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS120) {ENABLE 1 MODE 2V_unipolar NAME VCCAUX AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 7} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS121) {ENABLE 1 MODE 2V_unipolar NAME VCCAUX_PMC AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 8} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS122) {ENABLE 1 MODE 2V_unipolar NAME VCCAUX_SMON AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 9} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS123) {ENABLE 1 MODE 2V_unipolar NAME VCCINT AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 6} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS124) {ENABLE 1 MODE 4V_unipolar NAME VCCO_308 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 11} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS128) {ENABLE 1 MODE 4V_unipolar NAME VCCO_500 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 12} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS129) {ENABLE 1 MODE 4V_unipolar NAME VCCO_501 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 13} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS130) {ENABLE 1 MODE 4V_unipolar NAME VCCO_503 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 14} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS131) {ENABLE 1 MODE 2V_unipolar NAME VCCO_700 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 15} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS132) {ENABLE 1 MODE 2V_unipolar NAME VCCO_701 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 16} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS133) {ENABLE 1 MODE 2V_unipolar NAME VCCO_702 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 17} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS134) {ENABLE 1 MODE 2V_unipolar NAME VCCO_703 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 18} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS135) {ENABLE 1 MODE 2V_unipolar NAME VCCO_704 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 19} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS136) {ENABLE 1 MODE 2V_unipolar NAME VCCO_705 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 20} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS137) {ENABLE 1 MODE 2V_unipolar NAME VCCO_706 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 21} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS138) {ENABLE 1 MODE 2V_unipolar NAME VCCO_707 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 22} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS139) {ENABLE 1 MODE 2V_unipolar NAME VCCO_708 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 23} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS140) {ENABLE 1 MODE 2V_unipolar NAME VCCO_709 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 24} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS141) {ENABLE 1 MODE 2V_unipolar NAME VCCO_710 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 25} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS142) {ENABLE 1 MODE 2V_unipolar NAME VCCO_711 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 26} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS16) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVTT_110 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 45} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS17) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVTT_111 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 46} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS179) {ENABLE 1 MODE 2V_unipolar NAME VCC_BATT AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 0} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS180) {ENABLE 1 MODE 2V_unipolar NAME VCC_PMC AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 1} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS181) {ENABLE 1 MODE 2V_unipolar NAME VCC_PSFP AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 2} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS182) {ENABLE 1 MODE 2V_unipolar NAME VCC_PSLP AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 3} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS183) {ENABLE 1 MODE 2V_unipolar NAME VCC_RAM AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 4} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS184) {ENABLE 1 MODE 2V_unipolar NAME VCC_SOC AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 5} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS185) {ENABLE 1 MODE 1V_unipolar NAME VP_VN AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 1.00 SUPPLY_NUM 10} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS24) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_102 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 49} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS25) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_103 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 50} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS26) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_104 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 51} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS27) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_105 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 52} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS28) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_106 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 53} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS29) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_107 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 54} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS30) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_108 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 55} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS31) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_109 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 56} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS56) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_102 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 37} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS57) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_103 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 38} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS58) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_104 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 39} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS59) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_105 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 40} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS60) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_106 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 41} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS61) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_107 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 42} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS62) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_108 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 43} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS63) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_109 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 44} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS8) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCC_110 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 35} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS88) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_102 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 27} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS89) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_103 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 28} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS9) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCC_111 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 36} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS90) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_104 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 29} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS91) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_105 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 30} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS92) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_106 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 31} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS93) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_107 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 32} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS94) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_108 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 33} \
    CONFIG.PS_PMC_CONFIG(SMON_MEAS95) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_109 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 34} \
    CONFIG.PS_PMC_CONFIG(SMON_PMBUS_ADDRESS) {0x18} \
    CONFIG.PS_PMC_CONFIG(SMON_PMBUS_UNRESTRICTED) {{}} \
    CONFIG.PS_PMC_CONFIG_1(PS_I2CSYSMON_PERIPHERAL) {ENABLE 0 IO_TYPE MIO IO PMC_MIO_0:1} \
    CONFIG.PS_PMC_CONFIG_1(PS_SLR_ID) {1} \
    CONFIG.PS_PMC_CONFIG_1(SMON_INTERFACE_TO_USE) {I2C} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS0) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCCAUX_110 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 47} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS1) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCCAUX_111 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 48} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS120) {ENABLE 1 MODE 2V_unipolar NAME VCCAUX AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 7} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS121) {ENABLE 1 MODE 2V_unipolar NAME VCCAUX_PMC AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 8} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS122) {ENABLE 1 MODE 2V_unipolar NAME VCCAUX_SMON AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 9} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS123) {ENABLE 1 MODE 2V_unipolar NAME VCCINT AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 6} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS124) {ENABLE 1 MODE 4V_unipolar NAME VCCO_308 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 11} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS128) {ENABLE 1 MODE 4V_unipolar NAME VCCO_500 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 12} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS129) {ENABLE 1 MODE 4V_unipolar NAME VCCO_501 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 13} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS130) {ENABLE 1 MODE 4V_unipolar NAME VCCO_503 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 14} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS131) {ENABLE 1 MODE 2V_unipolar NAME VCCO_700 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 15} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS132) {ENABLE 1 MODE 2V_unipolar NAME VCCO_701 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 16} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS133) {ENABLE 1 MODE 2V_unipolar NAME VCCO_702 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 17} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS134) {ENABLE 1 MODE 2V_unipolar NAME VCCO_703 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 18} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS135) {ENABLE 1 MODE 2V_unipolar NAME VCCO_704 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 19} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS136) {ENABLE 1 MODE 2V_unipolar NAME VCCO_705 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 20} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS137) {ENABLE 1 MODE 2V_unipolar NAME VCCO_706 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 21} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS138) {ENABLE 1 MODE 2V_unipolar NAME VCCO_707 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 22} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS139) {ENABLE 1 MODE 2V_unipolar NAME VCCO_708 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 23} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS140) {ENABLE 1 MODE 2V_unipolar NAME VCCO_709 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 24} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS141) {ENABLE 1 MODE 2V_unipolar NAME VCCO_710 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 25} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS142) {ENABLE 1 MODE 2V_unipolar NAME VCCO_711 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 26} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS16) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVTT_110 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 45} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS17) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVTT_111 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 46} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS179) {ENABLE 1 MODE 2V_unipolar NAME VCC_BATT AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 0} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS180) {ENABLE 1 MODE 2V_unipolar NAME VCC_PMC AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 1} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS181) {ENABLE 1 MODE 2V_unipolar NAME VCC_PSFP AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 2} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS182) {ENABLE 1 MODE 2V_unipolar NAME VCC_PSLP AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 3} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS183) {ENABLE 1 MODE 2V_unipolar NAME VCC_RAM AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 4} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS184) {ENABLE 1 MODE 2V_unipolar NAME VCC_SOC AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 5} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS185) {ENABLE 1 MODE 1V_unipolar NAME VP_VN AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 1.00 SUPPLY_NUM 10} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS24) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_102 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 49} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS25) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_103 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 50} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS26) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_104 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 51} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS27) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_105 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 52} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS28) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_106 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 53} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS29) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_107 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 54} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS30) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_108 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 55} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS31) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_109 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 56} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS56) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_102 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 37} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS57) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_103 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 38} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS58) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_104 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 39} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS59) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_105 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 40} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS60) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_106 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 41} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS61) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_107 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 42} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS62) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_108 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 43} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS63) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_109 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 44} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS8) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCC_110 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 35} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS88) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_102 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 27} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS89) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_103 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 28} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS9) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCC_111 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 36} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS90) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_104 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 29} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS91) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_105 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 30} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS92) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_106 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 31} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS93) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_107 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 32} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS94) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_108 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 33} \
    CONFIG.PS_PMC_CONFIG_1(SMON_MEAS95) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_109 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 34} \
    CONFIG.PS_PMC_CONFIG_1(SMON_PMBUS_ADDRESS) {0x18} \
    CONFIG.PS_PMC_CONFIG_1(SMON_PMBUS_UNRESTRICTED) {{}} \
    CONFIG.PS_PMC_CONFIG_2(PS_I2CSYSMON_PERIPHERAL) {ENABLE 0 IO_TYPE MIO IO PMC_MIO_0:1} \
    CONFIG.PS_PMC_CONFIG_2(PS_SLR_ID) {2} \
    CONFIG.PS_PMC_CONFIG_2(SMON_INTERFACE_TO_USE) {I2C} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS0) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCCAUX_110 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 47} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS1) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCCAUX_111 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 48} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS120) {ENABLE 1 MODE 2V_unipolar NAME VCCAUX AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 7} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS121) {ENABLE 1 MODE 2V_unipolar NAME VCCAUX_PMC AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 8} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS122) {ENABLE 1 MODE 2V_unipolar NAME VCCAUX_SMON AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 9} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS123) {ENABLE 1 MODE 2V_unipolar NAME VCCINT AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 6} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS124) {ENABLE 1 MODE 4V_unipolar NAME VCCO_308 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 11} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS128) {ENABLE 1 MODE 4V_unipolar NAME VCCO_500 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 12} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS129) {ENABLE 1 MODE 4V_unipolar NAME VCCO_501 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 13} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS130) {ENABLE 1 MODE 4V_unipolar NAME VCCO_503 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 14} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS131) {ENABLE 1 MODE 2V_unipolar NAME VCCO_700 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 15} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS132) {ENABLE 1 MODE 2V_unipolar NAME VCCO_701 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 16} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS133) {ENABLE 1 MODE 2V_unipolar NAME VCCO_702 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 17} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS134) {ENABLE 1 MODE 2V_unipolar NAME VCCO_703 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 18} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS135) {ENABLE 1 MODE 2V_unipolar NAME VCCO_704 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 19} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS136) {ENABLE 1 MODE 2V_unipolar NAME VCCO_705 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 20} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS137) {ENABLE 1 MODE 2V_unipolar NAME VCCO_706 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 21} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS138) {ENABLE 1 MODE 2V_unipolar NAME VCCO_707 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 22} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS139) {ENABLE 1 MODE 2V_unipolar NAME VCCO_708 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 23} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS140) {ENABLE 1 MODE 2V_unipolar NAME VCCO_709 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 24} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS141) {ENABLE 1 MODE 2V_unipolar NAME VCCO_710 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 25} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS142) {ENABLE 1 MODE 2V_unipolar NAME VCCO_711 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 26} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS16) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVTT_110 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 45} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS17) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVTT_111 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 46} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS179) {ENABLE 1 MODE 2V_unipolar NAME VCC_BATT AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 0} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS180) {ENABLE 1 MODE 2V_unipolar NAME VCC_PMC AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 1} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS181) {ENABLE 1 MODE 2V_unipolar NAME VCC_PSFP AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 2} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS182) {ENABLE 1 MODE 2V_unipolar NAME VCC_PSLP AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 3} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS183) {ENABLE 1 MODE 2V_unipolar NAME VCC_RAM AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 4} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS184) {ENABLE 1 MODE 2V_unipolar NAME VCC_SOC AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 5} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS185) {ENABLE 1 MODE 1V_unipolar NAME VP_VN AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 1.00 SUPPLY_NUM 10} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS24) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_102 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 49} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS25) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_103 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 50} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS26) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_104 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 51} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS27) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_105 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 52} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS28) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_106 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 53} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS29) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_107 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 54} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS30) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_108 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 55} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS31) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_109 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 56} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS56) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_102 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 37} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS57) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_103 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 38} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS58) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_104 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 39} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS59) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_105 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 40} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS60) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_106 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 41} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS61) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_107 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 42} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS62) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_108 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 43} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS63) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_109 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 44} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS8) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCC_110 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 35} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS88) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_102 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 27} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS89) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_103 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 28} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS9) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCC_111 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 36} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS90) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_104 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 29} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS91) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_105 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 30} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS92) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_106 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 31} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS93) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_107 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 32} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS94) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_108 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 33} \
    CONFIG.PS_PMC_CONFIG_2(SMON_MEAS95) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_109 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 34} \
    CONFIG.PS_PMC_CONFIG_2(SMON_PMBUS_ADDRESS) {0x18} \
    CONFIG.PS_PMC_CONFIG_2(SMON_PMBUS_UNRESTRICTED) {{}} \
    CONFIG.PS_PMC_CONFIG_3(PS_I2CSYSMON_PERIPHERAL) {ENABLE 0 IO_TYPE MIO IO PMC_MIO_0:1} \
    CONFIG.PS_PMC_CONFIG_3(PS_SLR_ID) {3} \
    CONFIG.PS_PMC_CONFIG_3(SMON_INTERFACE_TO_USE) {I2C} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS0) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCCAUX_110 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 47} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS1) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCCAUX_111 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 48} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS120) {ENABLE 1 MODE 2V_unipolar NAME VCCAUX AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 7} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS121) {ENABLE 1 MODE 2V_unipolar NAME VCCAUX_PMC AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 8} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS122) {ENABLE 1 MODE 2V_unipolar NAME VCCAUX_SMON AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 9} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS123) {ENABLE 1 MODE 2V_unipolar NAME VCCINT AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 6} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS124) {ENABLE 1 MODE 4V_unipolar NAME VCCO_308 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 11} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS128) {ENABLE 1 MODE 4V_unipolar NAME VCCO_500 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 12} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS129) {ENABLE 1 MODE 4V_unipolar NAME VCCO_501 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 13} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS130) {ENABLE 1 MODE 4V_unipolar NAME VCCO_503 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 4.00 SUPPLY_NUM 14} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS131) {ENABLE 1 MODE 2V_unipolar NAME VCCO_700 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 15} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS132) {ENABLE 1 MODE 2V_unipolar NAME VCCO_701 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 16} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS133) {ENABLE 1 MODE 2V_unipolar NAME VCCO_702 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 17} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS134) {ENABLE 1 MODE 2V_unipolar NAME VCCO_703 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 18} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS135) {ENABLE 1 MODE 2V_unipolar NAME VCCO_704 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 19} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS136) {ENABLE 1 MODE 2V_unipolar NAME VCCO_705 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 20} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS137) {ENABLE 1 MODE 2V_unipolar NAME VCCO_706 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 21} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS138) {ENABLE 1 MODE 2V_unipolar NAME VCCO_707 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 22} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS139) {ENABLE 1 MODE 2V_unipolar NAME VCCO_708 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 23} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS140) {ENABLE 1 MODE 2V_unipolar NAME VCCO_709 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 24} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS141) {ENABLE 1 MODE 2V_unipolar NAME VCCO_710 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 25} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS142) {ENABLE 1 MODE 2V_unipolar NAME VCCO_711 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 26} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS16) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVTT_110 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 45} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS17) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVTT_111 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 46} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS179) {ENABLE 1 MODE 2V_unipolar NAME VCC_BATT AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 0} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS180) {ENABLE 1 MODE 2V_unipolar NAME VCC_PMC AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 1} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS181) {ENABLE 1 MODE 2V_unipolar NAME VCC_PSFP AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 2} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS182) {ENABLE 1 MODE 2V_unipolar NAME VCC_PSLP AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 3} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS183) {ENABLE 1 MODE 2V_unipolar NAME VCC_RAM AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 4} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS184) {ENABLE 1 MODE 2V_unipolar NAME VCC_SOC AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 5} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS185) {ENABLE 1 MODE 1V_unipolar NAME VP_VN AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 1.00 SUPPLY_NUM 10} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS24) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_102 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 49} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS25) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_103 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 50} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS26) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_104 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 51} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS27) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_105 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 52} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS28) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_106 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 53} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS29) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_107 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 54} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS30) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_108 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 55} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS31) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCCAUX_109 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 56} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS56) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_102 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 37} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS57) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_103 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 38} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS58) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_104 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 39} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS59) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_105 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 40} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS60) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_106 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 41} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS61) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_107 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 42} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS62) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_108 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 43} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS63) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVCC_109 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 44} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS8) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCC_110 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 35} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS88) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_102 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 27} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS89) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_103 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 28} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS9) {ENABLE 1 MODE 2V_unipolar NAME GTM_AVCC_111 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 36} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS90) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_104 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 29} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS91) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_105 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 30} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS92) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_106 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 31} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS93) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_107 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 32} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS94) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_108 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 33} \
    CONFIG.PS_PMC_CONFIG_3(SMON_MEAS95) {ENABLE 1 MODE 2V_unipolar NAME GTYP_AVTT_109 AVERAGE_EN 0 ALARM_ENABLE 0 ALARM_LOWER 0.00 ALARM_UPPER 2.00 SUPPLY_NUM 34} \
    CONFIG.PS_PMC_CONFIG_3(SMON_PMBUS_ADDRESS) {0x18} \
  ] $versal_cips_0


  # Create instance: axi_noc_0, and set properties
  set axi_noc_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_noc:1.1 axi_noc_0 ]
  set_property -dict [list \
    CONFIG.MC_CASWRITELATENCY {18} \
    CONFIG.MC_CHAN_REGION1 {DDR_LOW1} \
    CONFIG.MC_DATAWIDTH {72} \
    CONFIG.MC_INPUTCLK0_PERIOD {9750} \
    CONFIG.MC_MEMORY_DEVICETYPE {SODIMMs} \
    CONFIG.MC_MEMORY_SPEEDGRADE {DDR4-2666V(19-19-19)} \
    CONFIG.MC_MEMORY_TIMEPERIOD0 {750} \
    CONFIG.MC_PRE_DEF_ADDR_MAP_SEL {ROW_COLUMN_BANK} \
    CONFIG.MC_RANK {2} \
    CONFIG.MC_ROWADDRESSWIDTH {17} \
    CONFIG.MC_TFAW {23250} \
    CONFIG.MC_TRAS {32250} \
    CONFIG.MC_TRRD_L {8} \
    CONFIG.MC_TWTR_S {3000} \
    CONFIG.NUM_CLKS {9} \
    CONFIG.NUM_MC {2} \
    CONFIG.NUM_MCP {4} \
    CONFIG.NUM_MI {0} \
    CONFIG.NUM_SI {9} \
  ] $axi_noc_0


  set_property -dict [ list \
   CONFIG.CONNECTIONS {MC_3 {read_bw {5} write_bw {5} read_avg_burst {4} write_avg_burst {4}}} \
   CONFIG.NOC_PARAMS {} \
   CONFIG.CATEGORY {ps_pmc} \
 ] [get_bd_intf_pins /axi_noc_0/S00_AXI]

  set_property -dict [ list \
   CONFIG.CONNECTIONS {MC_3 {read_bw {5} write_bw {5} read_avg_burst {4} write_avg_burst {4}}} \
   CONFIG.NOC_PARAMS {} \
   CONFIG.CATEGORY {ps_cci} \
 ] [get_bd_intf_pins /axi_noc_0/S01_AXI]

  set_property -dict [ list \
   CONFIG.CONNECTIONS {MC_0 {read_bw {5} write_bw {5} read_avg_burst {4} write_avg_burst {4}}} \
   CONFIG.NOC_PARAMS {} \
   CONFIG.CATEGORY {ps_cci} \
 ] [get_bd_intf_pins /axi_noc_0/S02_AXI]

  set_property -dict [ list \
   CONFIG.CONNECTIONS {MC_0 {read_bw {5} write_bw {5} read_avg_burst {4} write_avg_burst {4}}} \
   CONFIG.NOC_PARAMS {} \
   CONFIG.CATEGORY {ps_nci} \
 ] [get_bd_intf_pins /axi_noc_0/S03_AXI]

  set_property -dict [ list \
   CONFIG.CONNECTIONS {MC_1 {read_bw {5} write_bw {5} read_avg_burst {4} write_avg_burst {4}}} \
   CONFIG.NOC_PARAMS {} \
   CONFIG.CATEGORY {ps_cci} \
 ] [get_bd_intf_pins /axi_noc_0/S04_AXI]

  set_property -dict [ list \
   CONFIG.CONNECTIONS {MC_1 {read_bw {5} write_bw {5} read_avg_burst {4} write_avg_burst {4}}} \
   CONFIG.NOC_PARAMS {} \
   CONFIG.CATEGORY {ps_nci} \
 ] [get_bd_intf_pins /axi_noc_0/S05_AXI]

  set_property -dict [ list \
   CONFIG.CONNECTIONS {MC_2 {read_bw {5} write_bw {5} read_avg_burst {4} write_avg_burst {4}}} \
   CONFIG.NOC_PARAMS {} \
   CONFIG.CATEGORY {ps_cci} \
 ] [get_bd_intf_pins /axi_noc_0/S06_AXI]

  set_property -dict [ list \
   CONFIG.CONNECTIONS {MC_2 {read_bw {5} write_bw {5} read_avg_burst {4} write_avg_burst {4}}} \
   CONFIG.NOC_PARAMS {} \
   CONFIG.CATEGORY {ps_rpu} \
 ] [get_bd_intf_pins /axi_noc_0/S07_AXI]

  set_property -dict [ list \
   CONFIG.CONNECTIONS {MC_1 {read_bw {500} write_bw {500} read_avg_burst {4} write_avg_burst {4}}} \
   CONFIG.NOC_PARAMS {} \
   CONFIG.CATEGORY {pl} \
 ] [get_bd_intf_pins /axi_noc_0/S08_AXI]

  set_property -dict [ list \
   CONFIG.ASSOCIATED_BUSIF {S00_AXI} \
 ] [get_bd_pins /axi_noc_0/aclk0]

  set_property -dict [ list \
   CONFIG.ASSOCIATED_BUSIF {S01_AXI} \
 ] [get_bd_pins /axi_noc_0/aclk1]

  set_property -dict [ list \
   CONFIG.ASSOCIATED_BUSIF {S02_AXI} \
 ] [get_bd_pins /axi_noc_0/aclk2]

  set_property -dict [ list \
   CONFIG.ASSOCIATED_BUSIF {S03_AXI} \
 ] [get_bd_pins /axi_noc_0/aclk3]

  set_property -dict [ list \
   CONFIG.ASSOCIATED_BUSIF {S04_AXI} \
 ] [get_bd_pins /axi_noc_0/aclk4]

  set_property -dict [ list \
   CONFIG.ASSOCIATED_BUSIF {S05_AXI} \
 ] [get_bd_pins /axi_noc_0/aclk5]

  set_property -dict [ list \
   CONFIG.ASSOCIATED_BUSIF {S06_AXI} \
 ] [get_bd_pins /axi_noc_0/aclk6]

  set_property -dict [ list \
   CONFIG.ASSOCIATED_BUSIF {S07_AXI} \
 ] [get_bd_pins /axi_noc_0/aclk7]

  set_property -dict [ list \
   CONFIG.ASSOCIATED_BUSIF {S08_AXI} \
 ] [get_bd_pins /axi_noc_0/aclk8]

  # Create interface connections
  connect_bd_intf_net -intf_net S08_AXI_0_1 [get_bd_intf_ports S08_AXI_0] [get_bd_intf_pins axi_noc_0/S08_AXI]
  connect_bd_intf_net -intf_net axi_noc_0_CH0_DDR4_0 [get_bd_intf_ports CH0_DDR4_0_0] [get_bd_intf_pins axi_noc_0/CH0_DDR4_0]
  connect_bd_intf_net -intf_net axi_noc_0_CH0_DDR4_1 [get_bd_intf_ports CH0_DDR4_1_0] [get_bd_intf_pins axi_noc_0/CH0_DDR4_1]
  connect_bd_intf_net -intf_net sys_clk0_0_1 [get_bd_intf_ports sys_clk0_0] [get_bd_intf_pins axi_noc_0/sys_clk0]
  connect_bd_intf_net -intf_net sys_clk1_0_1 [get_bd_intf_ports sys_clk1_0] [get_bd_intf_pins axi_noc_0/sys_clk1]
  connect_bd_intf_net -intf_net versal_cips_0_FPD_AXI_NOC0 [get_bd_intf_pins versal_cips_0/FPD_AXI_NOC0] [get_bd_intf_pins axi_noc_0/S03_AXI]
  connect_bd_intf_net -intf_net versal_cips_0_FPD_AXI_NOC1 [get_bd_intf_pins versal_cips_0/FPD_AXI_NOC1] [get_bd_intf_pins axi_noc_0/S05_AXI]
  connect_bd_intf_net -intf_net versal_cips_0_FPD_CCI_NOC0 [get_bd_intf_pins versal_cips_0/FPD_CCI_NOC0] [get_bd_intf_pins axi_noc_0/S02_AXI]
  connect_bd_intf_net -intf_net versal_cips_0_FPD_CCI_NOC1 [get_bd_intf_pins versal_cips_0/FPD_CCI_NOC1] [get_bd_intf_pins axi_noc_0/S04_AXI]
  connect_bd_intf_net -intf_net versal_cips_0_FPD_CCI_NOC2 [get_bd_intf_pins versal_cips_0/FPD_CCI_NOC2] [get_bd_intf_pins axi_noc_0/S06_AXI]
  connect_bd_intf_net -intf_net versal_cips_0_FPD_CCI_NOC3 [get_bd_intf_pins versal_cips_0/FPD_CCI_NOC3] [get_bd_intf_pins axi_noc_0/S01_AXI]
  connect_bd_intf_net -intf_net versal_cips_0_LPD_AXI_NOC0 [get_bd_intf_pins versal_cips_0/LPD_AXI_NOC0] [get_bd_intf_pins axi_noc_0/S07_AXI]
  connect_bd_intf_net -intf_net versal_cips_0_PMC_AXI_NOC0 [get_bd_intf_pins versal_cips_0/PMC_AXI_NOC0] [get_bd_intf_pins axi_noc_0/S00_AXI]

  # Create port connections
  connect_bd_net -net clk_5MHz_1  [get_bd_ports clk_5MHz] \
  [get_bd_pins axi_noc_0/aclk8]
  connect_bd_net -net versal_cips_0_fpd_axi_noc0_clk  [get_bd_pins versal_cips_0/fpd_axi_noc0_clk] \
  [get_bd_pins axi_noc_0/aclk3]
  connect_bd_net -net versal_cips_0_fpd_axi_noc1_clk  [get_bd_pins versal_cips_0/fpd_axi_noc1_clk] \
  [get_bd_pins axi_noc_0/aclk5]
  connect_bd_net -net versal_cips_0_fpd_cci_noc0_clk  [get_bd_pins versal_cips_0/fpd_cci_noc0_clk] \
  [get_bd_pins axi_noc_0/aclk2]
  connect_bd_net -net versal_cips_0_fpd_cci_noc1_clk  [get_bd_pins versal_cips_0/fpd_cci_noc1_clk] \
  [get_bd_pins axi_noc_0/aclk4]
  connect_bd_net -net versal_cips_0_fpd_cci_noc2_clk  [get_bd_pins versal_cips_0/fpd_cci_noc2_clk] \
  [get_bd_pins axi_noc_0/aclk6]
  connect_bd_net -net versal_cips_0_fpd_cci_noc3_clk  [get_bd_pins versal_cips_0/fpd_cci_noc3_clk] \
  [get_bd_pins axi_noc_0/aclk1]
  connect_bd_net -net versal_cips_0_lpd_axi_noc0_clk  [get_bd_pins versal_cips_0/lpd_axi_noc0_clk] \
  [get_bd_pins axi_noc_0/aclk7]
  connect_bd_net -net versal_cips_0_pmc_axi_noc0_clk  [get_bd_pins versal_cips_0/pmc_axi_noc0_clk] \
  [get_bd_pins axi_noc_0/aclk0]

  # Create address segments
  assign_bd_address -offset 0x08000000 -range 0x08000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_0] [get_bd_addr_segs axi_noc_0/S02_AXI/C0_DDR_LOW0x2] -force
  assign_bd_address -offset 0x000880000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_0] [get_bd_addr_segs axi_noc_0/S02_AXI/C0_DDR_LOW1x2] -force
  assign_bd_address -offset 0x10000000 -range 0x08000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_0] [get_bd_addr_segs axi_noc_0/S04_AXI/C1_DDR_LOW0x2] -force
  assign_bd_address -offset 0x000900000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_0] [get_bd_addr_segs axi_noc_0/S04_AXI/C1_DDR_LOW1x2] -force
  assign_bd_address -offset 0x18000000 -range 0x08000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_0] [get_bd_addr_segs axi_noc_0/S06_AXI/C2_DDR_LOW0x2] -force
  assign_bd_address -offset 0x000980000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_0] [get_bd_addr_segs axi_noc_0/S06_AXI/C2_DDR_LOW1x2] -force
  assign_bd_address -offset 0x00000000 -range 0x08000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_0] [get_bd_addr_segs axi_noc_0/S01_AXI/C3_DDR_LOW0x2] -force
  assign_bd_address -offset 0x000800000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_0] [get_bd_addr_segs axi_noc_0/S01_AXI/C3_DDR_LOW1x2] -force
  assign_bd_address -offset 0x08000000 -range 0x08000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_1] [get_bd_addr_segs axi_noc_0/S02_AXI/C0_DDR_LOW0x2] -force
  assign_bd_address -offset 0x000880000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_1] [get_bd_addr_segs axi_noc_0/S02_AXI/C0_DDR_LOW1x2] -force
  assign_bd_address -offset 0x10000000 -range 0x08000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_1] [get_bd_addr_segs axi_noc_0/S04_AXI/C1_DDR_LOW0x2] -force
  assign_bd_address -offset 0x000900000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_1] [get_bd_addr_segs axi_noc_0/S04_AXI/C1_DDR_LOW1x2] -force
  assign_bd_address -offset 0x18000000 -range 0x08000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_1] [get_bd_addr_segs axi_noc_0/S06_AXI/C2_DDR_LOW0x2] -force
  assign_bd_address -offset 0x000980000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_1] [get_bd_addr_segs axi_noc_0/S06_AXI/C2_DDR_LOW1x2] -force
  assign_bd_address -offset 0x00000000 -range 0x08000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_1] [get_bd_addr_segs axi_noc_0/S01_AXI/C3_DDR_LOW0x2] -force
  assign_bd_address -offset 0x000800000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexa72_1] [get_bd_addr_segs axi_noc_0/S01_AXI/C3_DDR_LOW1x2] -force
  assign_bd_address -offset 0x08000000 -range 0x04000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_0] [get_bd_addr_segs axi_noc_0/S02_AXI/C0_DDR_LOW0x2] -force
  assign_bd_address -offset 0x0C000000 -range 0x04000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_0] [get_bd_addr_segs axi_noc_0/S04_AXI/C1_DDR_LOW0x2] -force
  assign_bd_address -offset 0x14000000 -range 0x04000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_0] [get_bd_addr_segs axi_noc_0/S07_AXI/C2_DDR_LOW0x2] -force
  assign_bd_address -offset 0x10000000 -range 0x04000000 -with_name SEG_axi_noc_0_C2_DDR_LOW0x2_1 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_0] [get_bd_addr_segs axi_noc_0/S06_AXI/C2_DDR_LOW0x2] -force
  assign_bd_address -offset 0x04000000 -range 0x04000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_0] [get_bd_addr_segs axi_noc_0/S01_AXI/C3_DDR_LOW0x2] -force
  assign_bd_address -offset 0x00000000 -range 0x04000000 -with_name SEG_axi_noc_0_C3_DDR_LOW0x2_1 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_0] [get_bd_addr_segs axi_noc_0/S00_AXI/C3_DDR_LOW0x2] -force
  assign_bd_address -offset 0x08000000 -range 0x04000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_1] [get_bd_addr_segs axi_noc_0/S02_AXI/C0_DDR_LOW0x2] -force
  assign_bd_address -offset 0x0C000000 -range 0x04000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_1] [get_bd_addr_segs axi_noc_0/S04_AXI/C1_DDR_LOW0x2] -force
  assign_bd_address -offset 0x14000000 -range 0x04000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_1] [get_bd_addr_segs axi_noc_0/S07_AXI/C2_DDR_LOW0x2] -force
  assign_bd_address -offset 0x10000000 -range 0x04000000 -with_name SEG_axi_noc_0_C2_DDR_LOW0x2_1 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_1] [get_bd_addr_segs axi_noc_0/S06_AXI/C2_DDR_LOW0x2] -force
  assign_bd_address -offset 0x04000000 -range 0x04000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_1] [get_bd_addr_segs axi_noc_0/S01_AXI/C3_DDR_LOW0x2] -force
  assign_bd_address -offset 0x00000000 -range 0x04000000 -with_name SEG_axi_noc_0_C3_DDR_LOW0x2_1 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_1] [get_bd_addr_segs axi_noc_0/S00_AXI/C3_DDR_LOW0x2] -force
  assign_bd_address -offset 0x00000000 -range 0x10000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_dpc_0] [get_bd_addr_segs axi_noc_0/S00_AXI/C3_DDR_LOW0x2] -force
  assign_bd_address -offset 0x000800000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_dpc_0] [get_bd_addr_segs axi_noc_0/S00_AXI/C3_DDR_LOW1x2] -force
  assign_bd_address -offset 0x00000000 -range 0x10000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_pmc_0] [get_bd_addr_segs axi_noc_0/S00_AXI/C3_DDR_LOW0x2] -force
  assign_bd_address -offset 0x000800000000 -range 0x80000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_pmc_0] [get_bd_addr_segs axi_noc_0/S00_AXI/C3_DDR_LOW1x2] -force
  assign_bd_address -offset 0x10000000 -range 0x10000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_psm_0] [get_bd_addr_segs axi_noc_0/S07_AXI/C2_DDR_LOW0x2] -force
  assign_bd_address -offset 0x00000000 -range 0x10000000 -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_psm_0] [get_bd_addr_segs axi_noc_0/S00_AXI/C3_DDR_LOW0x2] -force
  assign_bd_address -offset 0x00000000 -range 0x20000000 -target_address_space [get_bd_addr_spaces S08_AXI_0] [get_bd_addr_segs axi_noc_0/S08_AXI/C1_DDR_LOW0x2] -force
  assign_bd_address -offset 0x000800000000 -range 0x000200000000 -target_address_space [get_bd_addr_spaces S08_AXI_0] [get_bd_addr_segs axi_noc_0/S08_AXI/C1_DDR_LOW1x2] -force

  # Exclude Address Segments
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_0] [get_bd_addr_segs axi_noc_0/S02_AXI/C0_DDR_LOW1x2]
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_0] [get_bd_addr_segs axi_noc_0/S04_AXI/C1_DDR_LOW1x2]
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_0] [get_bd_addr_segs axi_noc_0/S07_AXI/C2_DDR_LOW1x2]
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_0] [get_bd_addr_segs axi_noc_0/S06_AXI/C2_DDR_LOW1x2]
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_0] [get_bd_addr_segs axi_noc_0/S01_AXI/C3_DDR_LOW1x2]
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_0] [get_bd_addr_segs axi_noc_0/S00_AXI/C3_DDR_LOW1x2]
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_1] [get_bd_addr_segs axi_noc_0/S02_AXI/C0_DDR_LOW1x2]
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_1] [get_bd_addr_segs axi_noc_0/S04_AXI/C1_DDR_LOW1x2]
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_1] [get_bd_addr_segs axi_noc_0/S07_AXI/C2_DDR_LOW1x2]
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_1] [get_bd_addr_segs axi_noc_0/S06_AXI/C2_DDR_LOW1x2]
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_1] [get_bd_addr_segs axi_noc_0/S01_AXI/C3_DDR_LOW1x2]
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_cortexr5_1] [get_bd_addr_segs axi_noc_0/S00_AXI/C3_DDR_LOW1x2]
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_psm_0] [get_bd_addr_segs axi_noc_0/S07_AXI/C2_DDR_LOW1x2]
  exclude_bd_addr_seg -target_address_space [get_bd_addr_spaces versal_cips_0/pmcps_0_psv_psm_0] [get_bd_addr_segs axi_noc_0/S00_AXI/C3_DDR_LOW1x2]


  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
}
# End of create_root_design()


##################################################################
# MAIN FLOW
##################################################################

create_root_design ""


